### ISSUE TITLE
dOrg Web Page Design (Logo, Branding)

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#1]
Success looks like:
1. High-Level Branding Goals
2. Logo
3. Page Mock-up(s)
4. Copy Text

Milestone Goal: https://github.com/dOrgTech/backlog/issues/24

**Comment by oshimony** [comment]
Diving into this this week. Focus on succinctly and concretely showing what end-to-end services dOrg provides clients, in addition to open-source infrastructure & research work (see README).
