### ISSUE TITLE
"DxDAO Generic Action" Clarification

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#10]
Ask:
- Understand planned path forward & usability upon release.
- Ask whether or not they support adding new schemes as part of their caching.

Future steps:
- Genesis DAO proposal for specing out the different implementations.

**Comment by oshimony** [comment]
Sprint review:
- 'action centric' refactoring: abstracting away from implementation as 'scheme' vs. 'generic action' 
- creating a workflow around testing out a new action in a live DAO (one-off), developing a generalized implementation, having it 'approved', creating an interface, etc..
- waiting on meeting with Adam to move forward

**Comment by dOrgJelli** [comment]
Under question:

**Comment by dOrgJelli** [comment]
Closing: This has evolved into the DAOaction work spearheaded by @gh1dra.
