### ISSUE TITLE
Token Bonding Scheme

### ISSUE THREAD

**Issue by oshimony** [dOrgTech/backlog#16]
Success looks like:
- [ ] DAOstack scheme that supports a token bonding (continuous organization) contract.

**Comment by dOrgJelli** [comment]
Milestone Goal: https://github.com/dOrgTech/backlog/issues/23

**Comment by oshimony** [comment]
Simple token bonding curve (SimpleTBC) scheme in progress [here](https://github.com/dOrgTech/DAOfeatures/tree/simpleTBC)

**Comment by oshimony** [comment]
This has morphed into the GECO grant app...
