### ISSUE TITLE
Create Initial dOrg Legal Entity

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#28]
Success looks like:
- [ ] We have a legal entity created within a jurisdiction.

Milestone Goal: https://github.com/dOrgTech/backlog/issues/18

**Comment by oshimony** [comment]
Spec still undergoing revision. Incorporation will commence after reviews and discussion with our legal partners this week.

**Comment by oshimony** [comment]
This has morphed into the BBLLC Pilot. Spec currently underway...

**Comment by ontologymachine** [comment]
when is BBLLC call this week? Oliver mentioned but hasn't sent the link yet
