### ISSUE TITLE
Bushwick Legal Hackathon Prep

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#29]
Success looks like:

- [x]  A problem statement for participants in the hackathon to design a solution around
- [x]  Problem statement describes dOrg's legal challenges, current status and what it hopes to achieve
- [x]  Reviewed and incorporated by the event organizers into the program

Milestone Goal: https://github.com/dOrgTech/backlog/issues/18

**Comment by oshimony** [comment]
Success looks like:
- A problem statement for participants in the hackathon to design a solution around
- Problem statement describes dOrg's legal challenges, current status and what it hopes to achieve
- Reviewed and incorporated by the event organizers into the program

**Comment by oshimony** [comment]
Workshop for the hackathon is being formulated with organizers.
