### ISSUE TITLE
DAOstack Partnership Refinement

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#30]
Success looks like:
- [ ] Our monthly invoices and stake in their economy is well defined.
- [ ] Our relationship with DAOstack is legally sound.
- [ ] We have a partnership document that's self descriptive and signed off on by both parties.

Milestone Goal: https://github.com/dOrgTech/backlog/issues/18 & https://github.com/dOrgTech/backlog/issues/17

Dependent on: https://github.com/dOrgTech/backlog/issues/28

**Comment by oshimony** [comment]
April 1 deadline

**Comment by oshimony** [comment]
Technical coordination ops have been solidified:
- biweekly engineering sync
- bimonthly milestone presentations
- telegram chat

Still TBD:
- regular non-technical (ecosystem / client / biz dev) sync
