### ISSUE TITLE
Client Process Refinement

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#32]
Success looks like:
- [x] Catalog of client opportunities.

Milestone Goal: https://github.com/dOrgTech/backlog/issues/24

**Comment by oshimony** [comment]
Catalogue compiled in "Ecosystem Resource Management" database in Notion - also added grant programs, DAOs, and legal partners to the catalogue.

This week, I will follow-up with all contacts initiated last week and will begin grant applications.

Also working on defining our internal process for dealing with new clients (understanding DAO possibilities, our tooling, configuration, reputation seeding, launch, post-launch support, etc...)
