### ISSUE TITLE
Document Action-Modules, Utility DAOs, Schemes

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#4]
Success looks like:
- The SmartContract work we've discussed thus far has been logged in the backlog with details.

**Comment by dOrgJelli** [comment]
Presentation:
https://docs.google.com/presentation/d/1L4pwGkeqadaMsofImceydz3a5H8dt9XZbk3-UDNTe6E/

**Comment by oshimony** [comment]
Above slideshow is the high level overview. More detailed documentation will follow as a part of [`this issue`](https://github.com/dOrgTech/backlog/issues/10)

**Comment by oshimony** [comment]
See in gdrive 'Ecosystem' folder:

- [PotentialCollaborators](https://docs.google.com/document/d/10swWUz5XnzkJpBlcsmk8t7FdHClTpdcTm0cO5dM7xo0) for example DAOactions, DAOschemes and DAOcomponents
- [ClientDAOs](https://docs.google.com/document/d/1q4LSGoPt87GFxPVFjH7tdAZrPvrD9fdce4mqdmaooyY) for Utility, Community, Grant and dApp DAO examples

And see [DAOactions RealtimeBoard](https://realtimeboard.com/app/board/o9J_kyTBqd0=/) for mockup
