### ISSUE TITLE
Initial dOrg Legal Framework Spec

### ISSUE THREAD

**Issue by dOrgJelli** [dOrgTech/backlog#8]
Success looks like:
- Identified key legal problems we're solving for.
- Researched / documented potential solutions.
- Next steps documented (as tasks).

Questions answered:
- What do we do now? Make it less awkward for DAOstack.
- How do we handle ourselves as a DAO with multiple contributors & multiple clients?

**Comment by dOrgJelli** [comment]
@oshimony has created this document "dOrg Legal Framework(s)"

https://docs.google.com/document/d/1aeRxBrzZTvHqcdcARBCkewoQ_8rKrwQExwU8-YaeMHQ/edit#

**Comment by oshimony** [comment]
Exploratory frameworks doc created (linked above) + v0.1 spec
